apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - image: ellinj/loadgen-demo:latest
        imagePullPolicy: Always
        name: loadgen-demo
        env:
        - name: SPRING_APPLICATION
          value: load-gen
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      restartPolicy: Always
    