management:
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  zipkin:
    base-url: "http://zipkin-jellin.cfapps.io"
  sleuth:
    sampler:
      probability: 1



