management:
  metrics:
    web:
      server:
        auto-time-requests: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
        hello.time: true
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  sleuth:
    sampler:
      probability: 1
wavefront:
  application:
    name: jellin-demo
    service: hop2
server:
  port: 9999


