{
 "title": "Error Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": "label_values(kubernetes_name)" }
  ]
 },
 "panels": [
  {
   "title": "Error Rate by Instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_seconds_count{kubernetes_name=\"$application\", uri=\"/\", status=\"500\"}[1m]) or up{kubernetes_name=\"$application\"} * 0) / (sum by (instance) (rate(http_server_requests_seconds_count{kubernetes_name=\"$application\", uri=\"/\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(\n          http_server_requests_seconds_count{kubernetes_name=\"$application\", status!~\"[4-5].*\", uri=\"/\"}[30s]\n        )) / \n        sum(rate(\n          http_server_requests_seconds_count{kubernetes_name=\"$application\" , uri=\"/\"}[30s]\n        ))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response by Color",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (color) (rate(hello_total{kubernetes_name=\"$application\"}[30s]))",
     "legendFormat": "{{color}}"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(http_server_requests_seconds_count{kubernetes_name=\"$application\",uri=\"/\"}[1m]))\n",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}