management:
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  application:
    name: loadgen
  sleuth:
    web:
      additional-skip: "/actuator/prometheus"
    sampler:
      probability: 1
loadgen:
  url: 'http://localhost:8080'
server:
  port: 0
