management:
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  zipkin:
    base-url: "http://zipkin-jellin.cfapps.io"
  application:
    name: hop1
  sleuth:
    web:
      additional-skip: "/actuator/prometheus"
    sampler:
      probability: 1
loadgen:
  url: http://34.67.73.220
  
