apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: loadgen-deployment
  path: path-env-variables.yml