management:
  metrics:
    distribution:
       percentiles:
         http.client.requests: 0.95, 0.99
       sla:
         http.client.requests: 1ms,5ms
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  zipkin:
    base-url: "http://zipkin-jellin.cfapps.io"
  application:
    name: hop1
  sleuth:
    web:
      additional-skip: "/actuator/prometheus"
    sampler:
      probability: 1
#ribbon:
#  ServerListRefreshInterval: 1000 
eureka:
  client:
    registryFetchIntervalSeconds: 1
#   instance:
#     leaseRenewalIntervalInSeconds: 1
