management:
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  application:
    name: hop1
  sleuth:
    sampler:
      probability: 1

