management:
  metrics:
    distribution:
       percentiles-histogram:
           http.client.requests: true
           http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "metrics,prometheus,env"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    env:
      enabled: true
spring:
  sleuth:
    web:
      additional-skip: "/actuator/prometheus"
    sampler:
      probability: 1
wavefront:
  application:
    name: jellin-demo2
    service: hop1
hop2:
  url: http://localhost:8080/hop1